apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  selector:
    matchLabels:
      app: php
  replicas: 2
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: haamidir/my-laravel-pgsql-app:1.0.0
        ports:
        - containerPort: 9000